[package]
name = "syntax"
version = "0.0.0"
description = "Comment and whitespace preserving parser for the Rust language"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-analyzer/rust-analyzer"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.3"
rowan = "0.15.4"
rustc_lexer = { version = "725.0.0", package = "rustc-ap-rustc_lexer" }
rustc-hash = "1.1.0"
once_cell = "1.10.0"
indexmap = "1.8.0"
smol_str = "0.1.21"

stdx = { path = "../stdx", version = "0.0.0" }
text_edit = { path = "../text_edit", version = "0.0.0" }
parser = { path = "../parser", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }

[dev-dependencies]
rayon = "1.5.1"
expect-test = "1.2.2"
proc-macro2 = "1.0.36"
quote = "1.0.16"
ungrammar = "=1.16.1"

test_utils = { path = "../test_utils" }
sourcegen = { path = "../sourcegen" }
