[package]
name = "hir"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
rustc-hash = "1.1.0"
either = "1.6.1"
arrayvec = "0.7.2"
itertools = "0.10.3"
smallvec = "1.8.0"
once_cell = "1.10.0"

stdx = { path = "../stdx", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
base_db = { path = "../base_db", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
hir_expand = { path = "../hir_expand", version = "0.0.0" }
hir_def = { path = "../hir_def", version = "0.0.0" }
hir_ty = { path = "../hir_ty", version = "0.0.0" }
tt = { path = "../tt", version = "0.0.0" }
cfg = { path = "../cfg", version = "0.0.0" }
