[package]
name = "proc_macro_srv"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
object = { version = "0.28.3", default-features = false, features = [
    "std",
    "read_core",
    "elf",
    "macho",
    "pe",
] }
libloading = "0.7.3"
memmap2 = "0.5.3"

tt = { path = "../tt", version = "0.0.0" }
mbe = { path = "../mbe", version = "0.0.0" }
paths = { path = "../paths", version = "0.0.0" }
proc_macro_api = { path = "../proc_macro_api", version = "0.0.0" }

[dev-dependencies]
expect-test = "1.2.2"

# used as proc macro test targets
proc_macro_test = { path = "../proc_macro_test" }
