[package]
name = "flycheck"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
crossbeam-channel = "0.5.4"
tracing = "0.1.32"
cargo_metadata = "0.14.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
jod-thread = "0.1.2"

toolchain = { path = "../toolchain", version = "0.0.0" }
stdx = { path = "../stdx", version = "0.0.0" }
paths = { path = "../paths", version = "0.0.0" }
