[package]
name = "hir_ty"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.3"
arrayvec = "0.7.2"
smallvec = "1.8.0"
ena = "0.14.0"
tracing = "0.1.32"
rustc-hash = "1.1.0"
scoped-tls = "1.0.0"
chalk-solve = { version = "0.81.0", default-features = false }
chalk-ir = "0.81.0"
chalk-recursive = { version = "0.81.0", default-features = false }
la-arena = { version = "0.3.0", path = "../../lib/arena" }
once_cell = "1.10.0"
typed-arena = "2.0.1"

stdx = { path = "../stdx", version = "0.0.0" }
hir_def = { path = "../hir_def", version = "0.0.0" }
hir_expand = { path = "../hir_expand", version = "0.0.0" }
base_db = { path = "../base_db", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
limit = { path = "../limit", version = "0.0.0" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
expect-test = "1.2.2"
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.9", default-features = false, features = [
    "env-filter",
    "registry",
] }
tracing-tree = "0.2.0"
