[package]
name = "hir_def"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
dashmap = { version = "5.2.0", features = ["raw-api"] }
lock_api = "0.4.6"
parking_lot = "0.12.0"
tracing = "0.1.32"
once_cell = "1.10.0"
rustc-hash = "1.1.0"
either = "1.6.1"
anymap = "0.12.1"
drop_bomb = "0.1.5"
fst = { version = "0.4.7", default-features = false }
itertools = "0.10.3"
indexmap = "1.8.0"
smallvec = "1.8.0"
arrayvec = "0.7.2"
la-arena = { version = "0.3.0", path = "../../lib/arena" }

stdx = { path = "../stdx", version = "0.0.0" }
base_db = { path = "../base_db", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
hir_expand = { path = "../hir_expand", version = "0.0.0" }
mbe = { path = "../mbe", version = "0.0.0" }
cfg = { path = "../cfg", version = "0.0.0" }
tt = { path = "../tt", version = "0.0.0" }
limit = { path = "../limit", version = "0.0.0" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
expect-test = "1.2.2"
